api: 2

core: 8.x

projects:
  drupal: 8.1.x
  key_value: 1.x
  entity_storage_migrate:
    type: module
    download:
      type: git
      branch: make-users-non-revisionable
      url: "https://github.com/dickolsson/drupal-entity_storage_migrate.git"
  multiversion:
    type: module
    download:
      type: git
      branch: make-users-non-revisionable
      url: https://github.com/dickolsson/drupal-multiversion.git
